issue 116 - implemented request to get routes for ipv6 destinations
napalm-automation/napalm-iosxr pull request #117
Opened 2017-04-04 10:28 UTC by manuel-domke

implemented the xml request to get static routes for ipv6 destinations.

2017-04-04 12:03 UTC, manuel-domke commented
It seems to be impossible to improve code coverage (within scope of this project).

The test case for napalm_base only tests IPv4 at this time:
See https://github.com/napalm-automation/napalm-base/blob/develop/napalm_base/test/getters.py line 354ff:
    @wrap_test_cases
    def test_get_route_to(self, test_case):
        """Test get_route_to."""
        destination = '1.0.4.0/24'
  
When I add the test there, it will fail all/many napalm implementations?

2017-04-20 08:19 UTC, mirceaulinic requested changes
A small change please and we're ready to get this in.
Thanks @manuel-domke

2017-04-20 08:19 UTC, mirceaulinic commented on napalm_iosxr/iosxr.py
> +            return {'error': 'Wrong destination IP Address!'}
Please raise TypeError instead or returning a dictionary.

2017-04-28 11:39 UTC, mirceaulinic approved these changes

2017-04-28 11:39 UTC, merged

2017-04-28 11:39 UTC, mirceaulinic commented
Thanks @manuel-domke @thorko @juergen-geinitz

2017-05-31 14:05 UTC, mirceaulinic commented
This will be included in the next version, 0.5.0. Hope to be able to release it this week.